config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'static_pages#index'
  resources :static_pages, only: [:index]
  resources :templates, only: [:show]
  scope :api do
    scope :v1 do
      resources :templates, only: [:create, :index, :show]
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/index.html.erb
<%= content_for(:angular_app) do %>
  ng-app="indexApp"
  ng-controller="CommunityIndexCtrl"
<% end %>

<%= content_for(:community_cdns) do %>
  <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css"
    integrity="sha384-2hfp1SzUoho7/TsGGGDaFdsuuDL0LX2hnUp6VkX3CUQ2K4K+xjboZdsXyp4oUHZj"
    crossorigin="anonymous">
  <link rel="stylesheet"
  href='https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.1.1/css/mdb.min.css'>
  <%= stylesheet_link_tag 'jquery.fullPage.css'  %>
<% end %>

<div id="fullpage">
    <div class="section" id="main" style="background-image: url('/assets/bg-cta.jpg')">
    <h1>Welcome to Anglify BootStrap</h1>
      <button ng-click="getStarted()"
            class="btn btn-primary-outline waves-effect btn-lg">
        Get Started
      </button>
    </div>
    <div class="section" data-anchor="/choose">
      <div class="slide" data-anchor="slide1" style="background: yellow">
        <div class="section">

          <span>
            <h3 class="starting">Let's Get Started... </h3>
            <a id="go-to" class="fa fa-arrow-circle-right" aria-hidden="true"></a>
          </span>
        </div>
      </div>
      <div class="slide bg-faded" data-anchor="slide2">


        <div class="section">
          <div class="container">
            <!--Card-->
            <div ng-click="selectTemplate(template.id)" class="template-cards card col-xs-3" ng-repeat="template in templates" id="template{{template.id}}">
              <!--Card image-->
              <div class="view overlay hm-white-slight waves effect">
                <img src="{{template.image_url}}" class="img-fluid" alt="">
                  <a href="{{template.preview_url}}"
                  target="_blank" class="btn btn-md btn-success"> Preview </a>
              </a>
              </div>

            </div>
            <!--/.Card-->

            <!-- <div ng-if="isSelection()"> -->
              <%#= link_to 'Create your Portfolio Website!',  templates_path(template.id)%>
            <!-- </div> -->
            <div ng-if="isSelection()">
              <a href="templates/{{selected}}">Create your Portfolio Website!</a>
            </div>
            <button type="button"
                    id="submit-template"
                    ng-if="isSelection()"
                    class="btn btn-warning btn-lg btn-block">Create your Portfolio Website!</button>

          </div>
        </div>
      </div>
    </div>
</div>